Edu270 6
Maxdzy/eduMagenta2 pull request #5
Opened 2019-10-04 10:12 UTC by Maxdzy

Description

Create a simple sale badge extension that would allow the store owner to add a badge to a specific product. The badge management should happen on a separate Admin page.
Requirements

    List of currently created badges with name, status (active/disabled)

    Create page where the store owner can create a new badge entity and select badge image, name and activate/disable it

    Edit badge page where the store owner can change badge image, change its name and activate/disable it

    Mass action block with options to disable/enable multiple badges and delete selected badges

    In the frontend, the badge should be displayed in the top-left corner of the product image (anywhere it appears. Including Related products, Cross-sells, Product list etc...)

2019-10-07 07:19 UTC, Darvex requested changes
A lot of the comments that I left in specific files actually should be implemented in other files as well, please make sure you add php docs for methods and classes and code is styled accordingly

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/BadgesRepositoryInterface.php
> +    public function save(BadgesInterface $badges);
Please add return type, you seem to have it in the php docs (for all methods where it applies)

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/BadgesRepositoryInterface.php
> +    public function getById($badgeId);
Remove entire namespace, you already have it :)

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/Data/BadgesInterface.php
> +interface BadgesInterface
Please add php doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/BadgesRepositoryInterface.php
> + * Edu Admin Cagegory Map Record Save Controller.
This doesn't seem relevant to the file

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/Data/BadgesInterface.php
> +    public function getBadgeId($badgeId);
Please add return types and argument types where possible

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/Data/BadgesInterface.php
> +     * @return varchar
varchar is not php type

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Back.php
> +class Back extends Generic implements ButtonProviderInterface
Please add class php doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Generic.php
> +class Generic
Please add class doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Back.php
> +class Back extends Generic implements ButtonProviderInterface
I understand that Generic is in the same namespace as `Back` class, however it's good practice to add the namespace to `use` anyway

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Generic.php
> +     * @return int|null
I believe in interface it's defined is just Int

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Generic.php
> +    public function getUrl($route = '', $params = [])
please add return type

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Save.php
> +class Save extends Generic implements ButtonProviderInterface
Please add class doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Adminhtml/Badges/Edit/Buttons/Save.php
> +    public function getButtonData()
Please add return type

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +    public function __construct(
MIssing php doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +        if (isset($badgeIdList)) {
can just use `if($badeIdList)`

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Api/BadgesRepositoryInterface.php
> +    public function getBadgeId($badgeId);
Name of the function does not fit the description, one of those should be changed

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +                $badge = $this->badges->create()->load($id);
You created badges repository, why are you using deprecated load on model?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +                    if ($badge->getStatus() && $id != 0) {
Please use strict comparison

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +                    echo "error";
Please handle errors properly (either throw further exception or log it, or roll back the changes, whatever fits)

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +        return $result;
Please add empty line before return

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Related.php
> +class Related extends \Magento\Catalog\Block\Product\ProductList\Related
Class docs

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Related.php
> +
Remove unnecessary empty line

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Related.php
> +    public function renderBadge($badgeIdList = null)
You used exact same method in the previous block. Why not put this method in a separate class and inject it into any block you need it in? Also you could consider using trait for this (not ideal, but might be a good solution too)

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Related.php
> +
Please remove empty line

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductsList.php
> +//  Magento\CatalogWidget\Block\Product;
Please remove commented out code

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductsList.php
> +    public function renderBadge($badgeIdList = null)
Same as previously

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductsList.php
> +
Please remove empty line

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/View/Gallery.php
> +    public function __construct(
Missing php doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Block/Product/View/Gallery.php
> +    public function renderBadge($badgeIdList = null)
Same as previously

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> + * Class SomeCommand
Missing packages

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +class badgesList extends Command
classes start with capital letter

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +        $this->setDescription('This is badges console command.');
The description doesn't provide any info on what the command does

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +        $product = $this->objectManager->get('Magento\Catalog\Model\Product')->load($productId);
Object manager...

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +        $productId=5;
Hardcoded value. You can use value from the input instead

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +        $p = $product->getData('badges_list');
Please use proper variable names

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Console/Command/badgesList.php
> +     * @return null|int
I see that only null is returned, might as well not return void

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges.php
> +abstract class Badges extends Action
Is this class necessary? I don't think I've seen it used anywhere

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Add.php
> +
Please remove empty line

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Add.php
> +        return $resultForward->forward('edit');
Please add empty line before return

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Delete.php
> +        return $resultRedirect;
Please add empty line before return

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Edit.php
> +        if ($badgeId != null) {
Can just use `if($badgeId)`

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Edit.php
> +        //TODO change badges not work
Is this todo still necessary?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Edit.php
> +        return $resultPage;
Please add empty line before return

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/MassDelete.php
> +            $record->delete();
Is it possible to make mass delete?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Save.php
> +                $rowData = $this->badgesFactory->create();
You've created a model before, why do you need to create new one?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Save.php
> +                    return $resultRedirect->setPath('*/*/edit', ['badges_id' => $model->getId(), '_current' => true]);
Should there be `$rowData` instead of `$model`?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Save.php
> +                if ($this->getRequest()->getParam('back')) {
Please add empty line before this if

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges/Save.php
> +                return $resultRedirect->setPath('*/*/');
Missing empty line

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/Badges.php
> +        $this->uploaderPool    = $uploaderPool;
Please remove whitespaces before `= $uploaderPool`

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/Badges.php
> +        if ($badges) {
Don't need this if

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/Config/Source/BadgesSelect.php
> +    protected $options;
Missing php doc

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/Config/Source/BadgesSelect.php
> +        $this->options = [];
You can set empty array during variable declaration

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/DataProvider.php
> +        $this->meta = $this->prepareMeta($this->meta);
shouldn't `$meta` variable go into `prepareMeta()` ?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Model/DataProvider.php
> +        return $meta;
Only last meta is returned?

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Ui/Component/Listing/Column/BadgesActions.php
> +    public function prepareDataSource(array $dataSource)
This function is similar to previous file

2019-10-07 07:19 UTC, Darvex commented on app/code/Edu/CmsSimpleBadge/Ui/Component/Listing/Column/Image.php
> +        return isset($row[$altField]) ? $row[$altField] : null;
Try to return only a single type

2019-10-07 08:29 UTC, Maxdzy commented on app/code/Edu/CmsSimpleBadge/Controller/Adminhtml/Badges.php
> +abstract class Badges extends Action
![image](https://user-images.githubusercontent.com/29114471/66296187-d393bf00-e90e-11e9-8987-dd2c88c9f967.png)

2019-10-08 03:04 UTC, Maxdzy commented on app/code/Edu/CmsSimpleBadge/Block/Product/ProductList/Item/Block.php
> +                    if ($badge->getStatus() && $id != 0) {
make a check function in the model?

2019-10-10 09:11 UTC, merged